name: tugas_kesehatan_kebugaran
description: "Aplikasi Mobile Kesehatan & Kebugaran - Tugas Kelompok"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Supabase - untuk koneksi database & login dengan session
  supabase_flutter: ^2.17.2

  # Konversi kalender Hijriah
  hijri: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png" 
  # konfigurasi untuk Android modern (adaptive icon):
  adaptive_icon_background: "#FFFFFF" # warna latar belakang icon
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
